//__________________________DIALOGS
export const DIALOGS_CREATE_MESSAGE  = "DIALOGS-CREATE-MESSAGE"
export const DIALOGS_UPDATE_CURRENT_MESSAGE = "DIALOGS-UPDATE-CURRENT-MESSAGE"


//__________________________PROFILE
export const PROFILE_CREATE_POST = "PROFILE-CREATE-POST"
export const PROFILE_UPDATE_CURRENT_POST = "PROFILE-UPDATE-CURRENT-POST"

