//__________________________DIALOGS
export const DIALOGS_CREATE_MESSAGE  = "DIALOGS-CREATE-MESSAGE"
export const DIALOGS_UPDATE_CURRENT_MESSAGE = "DIALOGS-UPDATE-CURRENT-MESSAGE"


//__________________________PROFILE
export const PROFILE_CREATE_POST = "PROFILE-CREATE-POST"
export const PROFILE_UPDATE_CURRENT_POST = "PROFILE-UPDATE-CURRENT-POST"
export const PROFILE_LIKE_POST = "PROFILE_LIKE_POST"


//___________________________USERS
export const USERS_TOGGLE_FRIENDSHIP = "USERS_TOGGLE_FRIENDSHIP"
export const USERS_FETCH_USERS = "USERS_FETCH_USERS"
export const USERS_REDUCE_USERS = "USERS_REDUCE_USERS"
